### PR TITLE
Added PHONE_NUMBER test case

### LINKED ISSUE #10: Detect PHONE_NUMBER
A phone number is considered to be an important identifier that must be protected by a PII due to not only serving as a way to communicate directly with someone. Phone numbers allow people to determine the location and identity of the person identified through their number. Even though phone numbers across the globe are unique from one another, there are situations where they can be recycled and used by someone else once unclaimed by the number's previous user. Phone numbers can be considered an indirect way of identifying an individual since it isn't a permanent form of identification compared to a social security number. Phone numbers can be used as leverage for scammers to fish information and or promote scams that can jeopardize sensitive information from any of their targets.

Source: 
[Google AI](https://support.google.com/websearch/answer/14901683?hl=en&visit_id=638538137734319206-2434991030&p=ai_overviews&rd=1)
[Cloudflare](https://www.cloudflare.com/learning/privacy/what-is-pii/)

### PR DESCRIPTION
**Pull request by TiSuaBeh**

### CODE REVIEW

**Review by JalensMindset — APPROVED** [review]
Looks great!

**Comment by JaKhari2** [comment]
what about too long?

**Review by claesmk — APPROVED** [review]
Looks good

**Comment by claesmk** [comment]
@TiSuaBeh you can merge this now

**Pull request merged**
