### PR TITLE
Added IBAN_CODE test case

### LINKED ISSUE #21: Detect IBAN_CODE
An IBAN, or international bank account number, is a critical piece of personally identifiable information (PII) that contains a bank account holder's details for international transactions. It consists of a county code, check digits, a bank identifier, and a basic bank account number (BBAN). An IBAN is crucial to accurately detect and safeguard the IBAN code to ensure the precision and safety of international payments. Verification of the IBAN code is essential to prevent payment inaccuracies and to guarantee that funds reach the designated account on time. Additionally, it is important to prevent unauthorized access to the IBAN code to protect sensitive banking information and reduce the risk of fraudulent activities.

See [here](https://www.investopedia.com/terms/i/iban.asp) for more information on the IBAN code

### PR DESCRIPTION
**Pull request by Rahjion**

### CODE REVIEW

**Review by claesmk — APPROVED** [review]
This is OK, however, an improvement would be to construct the expected_result the same way the test_string is constructed which would hide the actual IBAN instead of having it hardcoded in a single string.

**Review by emaniem — COMMENTED** [review]
Everything here looks good!

**Review by emaniem — APPROVED** [review]
All changes look good.

**Review by donper7 — APPROVED** [review]
Looks good!

**Pull request merged**
