### PR TITLE
Added US_BANK_NUMBER test case

### LINKED ISSUE #8: Detecting US_BANK_NUMBER with Pattern match and context
One of the important personally identifiable information (PII) is your bank number. A bank account is your own personal account through a bank that will have your protected banking information. Your bank number is how you will identify your account. There are a lot of benefits to having a bank account. Once you open a checking account in your bank account, you will have a debit card for instant transactions and online pay without having to use cash. You can also open a savings account to save the money you wish to keep for the future and your bank can offer interest rates so you can earn more money the longer you save. With all this being said, it is essential to keep this particular PII secured. Attackers can get your bank number through phishing attacks, malware attacks, skimming devices, and more. So in, order to protect this PII, you're going to want to make sure your passwords are secured, secure your account with biometrics such as face ID and fingerprint, and not falling for scam emails. 

References/More information:
[here](https://www.pnc.com/insights/personal-finance/protect/how-to-protect-bank-account.html#:~:text=Taking%20proactive%20steps%20to%20safeguard,stay%20informed%20about%20key%20threats.)
[here](https://consumer.westchestergov.com/money-management/benefits-of-a-bank-account#:~:text=Bank%20accounts%20are%20cheaper&text=Paying%20bills%3A%20Without%20a%20bank,online%20at%20a%20low%20cost.)

### PR DESCRIPTION
**Pull request by JalensMindset**

### CODE REVIEW

**Comment by claesmk** [comment]
@JalensMindset are you using the vs code editor in code spaces unmodified?  It should be auto-indenting your code for you.  Not sure how you ended up with incorrect indentation 

image

**Review by claesmk — CHANGES_REQUESTED** [review]
Your negative test case is failing.  For the negative test case you would expect the string to not be replaced.  Like this:

```
         # Negative test case - Account length is less than 8
         test_account = "1234567"
         test_string = "My account number is " + test_account
         expected_result = "My account number is 1234567"
         actual_result = anonymize_text(test_string, ["US_BANK_NUMBER"])
         self.assertEqual(expected_result,
                        actual_result)
```

**Review by claesmk — APPROVED** [review]

**Comment by claesmk** [comment]
@JalensMindset I resolved the merge conflicts for you.  There was a comment out of place which made the merge a little more difficult than usual. Conflicts like this happen when two people from the same team work on the same file.  This is normal and is an important part of the team development process.  You just need one more review from your team and you can merge your PR

**Comment by claesmk** [comment]
@JalensMindset @SaintBaroque this is waiting on one more review.  After that it can be merged.

**Comment by SaintBaroque** [comment]
Great Work! @JalensMindset

**Review by SaintBaroque — APPROVED** [review]
Approved. Good Work!

**Pull request merged**
