### PR TITLE
adding positive IP ADDRESS test case

### LINKED ISSUE #11: Detect IP_ADDRESS
IP address detection is important for several reasons, most of which have to do with data analytics, network administration, and security. Devices linked to a network are identified uniquely by their IP addresses, which enables internet-based communication between them. Organizations use a variety of security measures, including firewalls, virtual private networks (VPNs), intrusion detection systems (IDS), intrusion prevention systems (IPS), and encryption protocols, to safeguard IP addresses and the related network infrastructure. Furthermore, to maintain a strong security posture and protect sensitive data, regular security audits, software updates, and personnel training are crucial.

For more info on IP address detection click[ here ](https://www.gdpreu.org/the-regulation/key-concepts/personal-data/)

### PR DESCRIPTION
**Pull request by shymik01**

### CODE REVIEW

**Review by claesmk — APPROVED** [review]
Looks good

**Comment by cmokoro** [comment]
what about identification for IP address class ranges?

**Review by cmokoro — APPROVED** [review]

**Review by cmokoro — APPROVED** [review]
Looks good and what about identification for IP address class ranges?

**Review by emaniem — APPROVED** [review]
Everything looks good. Have you considered various input formatting?

**Review by emaniem — COMMENTED** [review]
Looks good.

**Review by claesmk — APPROVED** [review]
Fixed up a few issues

**Pull request merged**
