### PR TITLE
Added Email PII Detection Test Cases

### LINKED ISSUE #13: DETECT (AND PROTECT) EMAIL_ADDRESS
In this task, we focus on detecting and protecting Email Addresses as a form of Personally Identifiable Information (PII). Email addresses are crucial to safeguard because they can be used to identify individuals, facilitate phishing attacks, and potentially lead to identity theft if exposed. Going further, the importance of detecting and protecting Email Addresses includes:
1. Privacy Protection
2. Security 
3. Compliance 
4. Trust

With Privacy Protection we are ensuring individuals Email Addresses are protected from unauthorized parties. Security prevents unauthorized access to someone's Email Address. This helps mitigate attacks such as phishing, and misuse of a person's email. Compliance is assuring we are following the standards and guidelines of data protection regulations such as GDPR and CCPA, which mandate PII protection. This brings piece of mind to a customer, and maintains user trust by ensuring their sensitive information is being handled responsibly. 

For more information about EMAIL_ADDRESS PII detection and best practices [click here](https://www.malwarebytes.com/cybersecurity/basics/pii)

### PR DESCRIPTION
**Pull request by donper7**

### CODE REVIEW

**Review by Rahjion — APPROVED** [review]
Good, everything looks to be in order.

**Review by emaniem — APPROVED** [review]
Everything look good.

**Review by Rahjion — APPROVED** [review]
Looks good

**Review by claesmk — APPROVED** [review]
You can merge this now

**Pull request merged**
